#!/usr/bin/env python3
from pathlib import Path

status_path = Path('docs/tracking/STATUS.md')
worklog_path = Path('docs/tracking/WORKLOG.md')
status = status_path.read_text(encoding='utf-8')

replacements = [
    ('version: 0.13.0', 'version: 0.14.0'),
    ('  - REVIEW-AURORA-M0-R1-APPLICABILITY-2026-08-07\nlast_reviewed:',
     '  - REVIEW-AURORA-M0-R1-APPLICABILITY-2026-08-07\n  - DOC-AURORA-M0-R2-OPERATOR-AUTHORIZATION\n  - DOC-AURORA-CAP-SOVEREIGN-CORE-REQUIREMENTS\n  - DOC-AURORA-CAP-SOVEREIGN-CORE-R2-COVERAGE\n  - REVIEW-AURORA-M0-R2-REQUIREMENTS-2026-08-07\nlast_reviewed:'),
    ('- **Current readiness gate:** ACRM R1 — Applicability — PASS',
     '- **Current readiness gate:** ACRM R2 — Requirements — PASS'),
    ('- **R1 active constitutional sources for future R2:** 127 (`78 APPLIES + 49 PARTIALLY_APPLIES`)\n- **R2 — Requirements:** NOT AUTHORIZED / awaiting explicit operator authorization\n- **R3 and later gates:** NOT AUTHORIZED BY IMPLICATION',
     '- **R1 active constitutional sources for R2:** 127 (`78 APPLIES + 49 PARTIALLY_APPLIES`)\n- **R2 source baseline:** `495b712142d7c3d722da2298f7a0b060707f9f5e`\n- **R2 reviewed requirements package:** `a8ffbbe22995b8e683d9d49ad06f487c745709f9`\n- **R2 derived requirements:** 122 proposed atomic requirements; coverage 127/127 active sources\n- **R2 canonical integration:** `9bfab2b30eaccb92ddb55852f97735653172f064`\n- **R2 verdict:** PASS\n- **R3 — Capability Readiness:** NOT AUTHORIZED / awaiting explicit operator authorization\n- **R4 and later gates:** NOT AUTHORIZED BY IMPLICATION'),
    ('The following remain open and were not decided by R0 or R1; they belong to later applicable readiness gates:',
     'The following remain open and were not decided by R0, R1 or R2; they belong to later applicable readiness gates:'),
    ('M0 ACRM R1 — Applicability:    PASS — source baseline 735f269025e2cc317424e4931f3a5cd414cd6f2a\nR1 applicability coverage:     294/294 classified; 127 active sources\nACRM R2 — Requirements:        NOT AUTHORIZED / AWAITING OPERATOR\nACRM R3+:                       NOT AUTHORIZED',
     'M0 ACRM R1 — Applicability:    PASS — source baseline 735f269025e2cc317424e4931f3a5cd414cd6f2a\nR1 applicability coverage:     294/294 classified; 127 active sources\nM0 ACRM R2 — Requirements:     PASS — source baseline 495b712142d7c3d722da2298f7a0b060707f9f5e\nR2 requirements baseline:       122 proposed atomic requirements; coverage 127/127\nACRM R3 — Capability Readiness: NOT AUTHORIZED / AWAITING OPERATOR\nACRM R4+:                       NOT AUTHORIZED'),
    ('The M0 ACRM R1 applicability analysis against fixed source baseline `735f269025e2cc317424e4931f3a5cd414cd6f2a` classified all 294 accepted constitutional requirements and returned `R1 PASS`. There is no unresolved `CONFLICT_REQUIRES_DECISION` and no unjustified exclusion identified by the R1 review.\n\nThe intentional boundary is now authorization: R2 has **not** been authorized. No atomic Capability requirement derivation, Capability/System Spec, threat-model execution, Architecture Spike, stack choice, Mission Contract, Microdesign or implementation may begin by implication.',
     'The M0 ACRM R2 requirements derivation against fixed source baseline `495b712142d7c3d722da2298f7a0b060707f9f5e` transformed all 127 R1-active constitutional source rows into a reviewed package of 122 proposed atomic requirements with 127/127 source coverage and returned `R2 PASS`. The R2-specific validator reported 0 uncovered active sources, 0 inactive source references, 0 unsupported verification methods and 0 selected technology candidates. Eight adversarial wording findings were corrected before the final verdict.\n\nThe requirements remain `proposed`; canonical integration and green CI do not constitute operator acceptance. The intentional boundary is now authorization: R3 has **not** been authorized. No Capability/System Spec, threat-model execution, Architecture Spike, stack choice, Mission Contract, Microdesign or implementation may begin by implication.'),
    ('R1 PASS recorded\n→ stop at the R1 boundary\n→ await explicit operator authorization for M0 ACRM R2 — Requirements',
     'R2 PASS recorded\n→ stop at the R2 boundary\n→ await explicit operator authorization for M0 ACRM R3 — Capability Readiness')
]
for old, new in replacements:
    count = status.count(old)
    if count != 1:
        raise SystemExit(f'expected exactly one STATUS occurrence, got {count}: {old[:100]}')
    status = status.replace(old, new)
status_path.write_text(status, encoding='utf-8')

worklog = worklog_path.read_text(encoding='utf-8').rstrip() + '''\n\n\n## 2026-08-07 — M0 R2 Requirements\n\nAfter R1 PASS, the operator explicitly authorized `M0 ACRM R2 — Requirements` with the statement `Entendi continue: Autorizo o M0 ACRM R2 — Requirements.` The authorization was recorded in `docs/acceptance/2026-08-07-m0-r2-operator-authorization.md`.\n\nR2 fixed its canonical source baseline at:\n\n```text\n495b712142d7c3d722da2298f7a0b060707f9f5e\n```\n\nThe R1-active set contained 127 constitutional source rows (`78 APPLIES + 49 PARTIALLY_APPLIES`). R2 derived 122 proposed atomic requirements at `docs/capabilities/CAP-SOVEREIGN-CORE/REQUIREMENTS.md` and mapped every active source in `docs/capabilities/CAP-SOVEREIGN-CORE/R2-COVERAGE.md`.\n\nMechanical package validation in GitHub Actions run `31149256807` reported:\n\n```text\nderived requirements: 122\nrisk distribution: critical=51, high=53, medium=18\nR1 active sources: 127\ncoverage rows: 127\nsource->requirement links: 409\nuncovered active sources: 0\ninactive source references: 0\nunsupported verification methods: 0\ncandidate technology selections: 0\n```\n\nThe adversarial review did not auto-pass the first draft. Eight wording defects were corrected before verdict: removal of an event/audit authority exception; removal of a sensitive-observability exception; narrowing archive/privacy scope; narrowing incident-response scope; correcting an overrestrictive durable-engine guard; strengthening artifact-reference and evolutionary-adapter modals to match constitutional strength; and tightening the M0 secret-hygiene boundary.\n\nThe clean requirements package target was:\n\n```text\na8ffbbe22995b8e683d9d49ad06f487c745709f9\n```\n\nThe formal review was recorded at `docs/reviews/2026-08-07-m0-r2-requirements-review.md` with verdict:\n\n```text\nR2 PASS\n```\n\nThe review itself passed documentation validation in workflow run `31149400264`, and the clean R2 package was fast-forward integrated into canonical `main` at `9bfab2b30eaccb92ddb55852f97735653172f064`. Normal main Documentation workflow run `31149443670` also completed successfully.\n\nThe 122 Capability requirements remain `status: proposed`; Git integration/CI is not operator acceptance. R2 did not select language/runtime, database/store, state/event mechanism, schema technology, telemetry backend, event transport, backup/migration tooling, topology, durable engine or Architecture Spike winner. R3 and later gates remain separately unauthorized.\n'''
worklog_path.write_text(worklog, encoding='utf-8')
print('Prepared M0 R2 tracking closeout.')
