package application

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/developmentconexus-ops/aurora_project/internal/domain/authority"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/project"
	"github.com/developmentconexus-ops/aurora_project/internal/ports"
)

var ErrStaleAuthorityRevision=ports.ErrStaleAuthorityRevision

type AuthorityView struct{State authority.State `json:"state"`}
type GrantAuthorityInput struct{ExpectedRevision authority.Revision;ProjectID project.ProjectID;ActionClass string;ValidUntil *time.Time}
type RevokeAuthorityInput struct{ExpectedRevision authority.Revision;AuthorityID authority.AuthorityID}

func decodeAuthorityState(raw []byte)(authority.State,error){var state authority.State;if err:=json.Unmarshal(raw,&state);err!=nil{return state,fmt.Errorf("decode authority state: %w",err)};if state.Revision==0{return state,errors.New("invalid zero authority revision")};return state,nil}
func(s *Service)ShowAuthority(ctx context.Context,ownerPassphrase []byte)(AuthorityView,error){trusted,err:=s.loadTrustedCurrent(ctx,ownerPassphrase);if err!=nil{return AuthorityView{},err};defer zero(trusted.ORK);state,err:=decodeAuthorityState(trusted.Snapshot.AuthorityStateJSON);if err!=nil{return AuthorityView{},err};return AuthorityView{State:state},nil}
func(s *Service)GrantAuthority(ctx context.Context,ownerPassphrase []byte,in GrantAuthorityInput)(AuthorityView,error){if in.ActionClass==""{return AuthorityView{},errors.New("authority action class is required")};trusted,err:=s.loadTrustedCurrent(ctx,ownerPassphrase);if err!=nil{return AuthorityView{},err};defer zero(trusted.ORK);current,err:=decodeAuthorityState(trusted.Snapshot.AuthorityStateJSON);if err!=nil{return AuthorityView{},err};if current.Revision!=in.ExpectedRevision{return AuthorityView{},ErrStaleAuthorityRevision};id,err:=authority.NewAuthorityID();if err!=nil{return AuthorityView{},err};now:=s.Clock.Now().UTC();scope:=[]project.ProjectID{"*"};if in.ProjectID!=""{scope=[]project.ProjectID{in.ProjectID}};grant:=authority.Grant{AuthorityID:id,AuthorityRevision:1,SubjectOperatorID:trusted.Snapshot.Identity.OwnerOperatorID,ActorID:"AURORA_CORE",ProjectScope:scope,PermittedActionClasses:[]string{in.ActionClass},ValidUntil:in.ValidUntil,LifecycleStatus:authority.Active,IssuedAt:now,Provenance:"owner-authority-admin"};nextRev:=current.Revision+1;pred:=current.Revision;next:=authority.State{Revision:nextRev,PredecessorRevision:&pred,Grants:append(append([]authority.Grant(nil),current.Grants...),grant),RevalidationRequired:current.RevalidationRequired,ChangedBy:string(trusted.Snapshot.Identity.OwnerOperatorID),ChangedAt:now};return s.commitAuthorityState(ctx,trusted,next,current.Revision,"OP-AUTH-GRANT-"+string(id))}
func(s *Service)RevokeAuthority(ctx context.Context,ownerPassphrase []byte,in RevokeAuthorityInput)(AuthorityView,error){trusted,err:=s.loadTrustedCurrent(ctx,ownerPassphrase);if err!=nil{return AuthorityView{},err};defer zero(trusted.ORK);current,err:=decodeAuthorityState(trusted.Snapshot.AuthorityStateJSON);if err!=nil{return AuthorityView{},err};if current.Revision!=in.ExpectedRevision{return AuthorityView{},ErrStaleAuthorityRevision};now:=s.Clock.Now().UTC();grants:=append([]authority.Grant(nil),current.Grants...);found:=false;for i:=range grants{if grants[i].AuthorityID==in.AuthorityID{if grants[i].LifecycleStatus!=authority.Active{return AuthorityView{},errors.New("authority is not active")};grants[i].AuthorityRevision++;grants[i].LifecycleStatus=authority.Revoked;grants[i].RevokedAt=&now;found=true}};if !found{return AuthorityView{},errors.New("authority not found")};nextRev:=current.Revision+1;pred:=current.Revision;next:=authority.State{Revision:nextRev,PredecessorRevision:&pred,Grants:grants,RevalidationRequired:current.RevalidationRequired,ChangedBy:string(trusted.Snapshot.Identity.OwnerOperatorID),ChangedAt:now};return s.commitAuthorityState(ctx,trusted,next,current.Revision,"OP-AUTH-REVOKE-"+string(in.AuthorityID))}
func(s *Service)commitAuthorityState(ctx context.Context,trusted trustedCurrent,next authority.State,expected authority.Revision,operationID string)(AuthorityView,error){raw,err:=json.Marshal(next);if err!=nil{return AuthorityView{},err};newSnap:=trusted.Snapshot;newSnap.AuthorityStateJSON=raw;newSnap.CurrentAuthorityRevision=uint64(next.Revision);newSnap.GoverningGeneration++;mac,err:=governingMAC(trusted.ORK,newSnap);if err!=nil{return AuthorityView{},err};persisted,err:=s.State.CommitAuthorityRevision(ctx,ports.AuthorityMutation{State:next,ExpectedAuthorityRevision:expected,ExpectedGeneration:trusted.Snapshot.GoverningGeneration,NewGeneration:newSnap.GoverningGeneration,GoverningMAC:mac,OperationID:operationID});if err!=nil{return AuthorityView{},err};anchor:=trusted.Anchor;anchor.GoverningGeneration=newSnap.GoverningGeneration;if next.ChangedAt.After(anchor.ObservedWallTimeHighWater){anchor.ObservedWallTimeHighWater=next.ChangedAt};am,err:=anchorMAC(trusted.ORK,anchor);if err!=nil{return AuthorityView{},err};anchor.HMAC=encodeMAC(am);if err:=s.Trust.PublishAnchor(ctx,anchor);err!=nil{return AuthorityView{},fmt.Errorf("publish authority anchor: %w",err)};return AuthorityView{State:persisted},nil}
