package application

import(
	"context";"encoding/json";"errors";"fmt";"io/fs"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/authority"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/identity"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/project"
	"github.com/developmentconexus-ops/aurora_project/internal/ports"
)
var ErrAlreadyInitialized=errors.New("Aurora is already initialized")
type InitializeResult struct{AuroraID identity.AuroraID `json:"aurora_id"`;OwnerOperatorID identity.OperatorID `json:"owner_operator_id"`;GoverningGeneration uint64 `json:"governing_generation"`}
func(s *Service)Initialize(ctx context.Context,passphrase []byte)(InitializeResult,error){if s.State==nil||s.Trust==nil||s.Clock==nil{return InitializeResult{},errors.New("service dependencies are incomplete")};if _,err:=s.Trust.LoadRootEnvelope(ctx);err==nil{return InitializeResult{},ErrAlreadyInitialized}else if !errors.Is(err,fs.ErrNotExist){return InitializeResult{},fmt.Errorf("check existing owner root: %w",err)};env,ork,err:=newRootEnvelope(passphrase);if err!=nil{return InitializeResult{},err};defer zero(ork);if err:=s.Trust.StoreRootEnvelope(ctx,env);err!=nil{return InitializeResult{},fmt.Errorf("publish owner root: %w",err)};auroraID,err:=identity.NewAuroraID();if err!=nil{return InitializeResult{},err};now:=s.Clock.Now().UTC();id:=identity.AuroraIdentity{AuroraID:auroraID,OwnerOperatorID:"OWNER-LEANDRO",CreatedAt:now,IdentityRevision:1,CapabilityContractVersion:"0.2.0"};initial:=authority.State{Revision:1,Grants:[]authority.Grant{{AuthorityID:"AUTH-OWNER-INITIAL",AuthorityRevision:1,SubjectOperatorID:"OWNER-LEANDRO",ActorID:"AURORA_CORE",ProjectScope:[]project.ProjectID{"*"},PermittedActionClasses:[]string{"project.create","project.state.transition","authority.admin","export","restore","migration"},LifecycleStatus:authority.Active,IssuedAt:now,Provenance:"owner-bootstrap"}},ChangedBy:"OWNER-LEANDRO",ChangedAt:now};authorityJSON,err:=json.Marshal(initial);if err!=nil{return InitializeResult{},err};snap:=ports.CurrentSnapshot{Identity:id,AuthorityStateJSON:authorityJSON,CurrentAuthorityRevision:1,GoverningGeneration:1};mac,err:=governingMAC(ork,snap);if err!=nil{return InitializeResult{},err};_,err=s.State.Bootstrap(ctx,ports.BootstrapMutation{Identity:id,AuthorityStateJSON:authorityJSON,CurrentAuthorityRevision:1,GoverningGeneration:1,GoverningMAC:mac});if err!=nil{return InitializeResult{},fmt.Errorf("bootstrap state: %w",err)};anchor:=ports.Anchor{Version:1,RootID:env.RootID,AuroraID:auroraID,GoverningGeneration:1,ObservedWallTimeHighWater:now};am,err:=anchorMAC(ork,anchor);if err!=nil{return InitializeResult{},err};anchor.HMAC=encodeMAC(am);if err:=s.Trust.PublishAnchor(ctx,anchor);err!=nil{return InitializeResult{},fmt.Errorf("publish owner anchor: %w",err)};return InitializeResult{AuroraID:auroraID,OwnerOperatorID:id.OwnerOperatorID,GoverningGeneration:1},nil}
