package application

import(
	"context";"encoding/json";"errors";"fmt"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/authority"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/identity"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/portability"
	"github.com/developmentconexus-ops/aurora_project/internal/ports"
)
var ErrRestoreTargetNotFresh=ports.ErrRestoreTargetNotFresh
var ErrRestoreNotRevalidatable=errors.New("restored authority is not in REVALIDATION_REQUIRED state")
type RestoreResult struct{ExportID string `json:"export_id"`;AuroraID identity.AuroraID `json:"aurora_id"`;AuthorityStateRevision uint64 `json:"authority_state_revision"`;GoverningGeneration uint64 `json:"governing_generation"`;TrustStatus TrustStatus `json:"trust_status"`}
func(s *Service)Restore(ctx context.Context,ciphertext,exportSecret,ownerPassphrase []byte)(RestoreResult,error){if s.ExportProtection==nil{return RestoreResult{},errors.New("export protection adapter is not configured")};plain,err:=s.ExportProtection.Unprotect(ctx,ciphertext,exportSecret);if err!=nil{return RestoreResult{},fmt.Errorf("unprotect export: %w",err)};var doc portability.Document;if err:=json.Unmarshal(plain,&doc);err!=nil{return RestoreResult{},fmt.Errorf("decode export JSON: %w",err)};if err:=portability.Verify(doc);err!=nil{return RestoreResult{},err};root:=portableToRoot(doc.OwnerRecovery);ork,err:=unlockORK(ownerPassphrase,root);if err!=nil{return RestoreResult{},fmt.Errorf("recover owner root: %w",err)};defer zero(ork);state:=storeStateFromDocument(doc);found:=false;for i:=range state.Authority.Revisions{if state.Authority.Revisions[i].Revision==state.Authority.CurrentRevision{state.Authority.Revisions[i].RevalidationRequired=true;found=true;break}};if !found{return RestoreResult{},errors.New("current authority revision absent from export")};snap,err:=storeStateToCurrentSnapshot(state);if err!=nil{return RestoreResult{},err};mac,err:=governingMAC(ork,snap);if err!=nil{return RestoreResult{},err};if err:=s.State.BuildFreshFromExport(ctx,ports.RestoreSnapshot{State:state,GoverningMAC:mac});err!=nil{if errors.Is(err,ports.ErrRestoreTargetNotFresh){return RestoreResult{},ErrRestoreTargetNotFresh};return RestoreResult{},err};if err:=s.Trust.StoreRootEnvelope(ctx,root);err!=nil{return RestoreResult{},fmt.Errorf("publish recovered owner root: %w",err)};now:=s.Clock.Now().UTC();anchor:=ports.Anchor{Version:1,RootID:root.RootID,AuroraID:state.Aurora.AuroraID,GoverningGeneration:state.GoverningGeneration,ObservedWallTimeHighWater:now};am,err:=anchorMAC(ork,anchor);if err!=nil{return RestoreResult{},err};anchor.HMAC=encodeMAC(am);if err:=s.Trust.PublishAnchor(ctx,anchor);err!=nil{return RestoreResult{},fmt.Errorf("publish restore anchor: %w",err)};classification,err:=s.ClassifyTrust(ctx,ownerPassphrase);if err!=nil{return RestoreResult{},err};if classification.Status!=TrustRevalidationRequired{return RestoreResult{},fmt.Errorf("restored trust status=%s want REVALIDATION_REQUIRED",classification.Status)};return RestoreResult{ExportID:doc.ExportID,AuroraID:state.Aurora.AuroraID,AuthorityStateRevision:uint64(state.Authority.CurrentRevision),GoverningGeneration:state.GoverningGeneration,TrustStatus:classification.Status},nil}
func(s *Service)RevalidateRestoredAuthority(ctx context.Context,ownerPassphrase []byte)error{assessment,err:=s.assessTrust(ctx,ownerPassphrase);if err!=nil{return err};defer func(){if assessment.ORK!=nil{zero(assessment.ORK)}}();if assessment.Result.Status!=TrustRevalidationRequired{return ErrRestoreNotRevalidatable};current,err:=decodeAuthorityState(assessment.Snapshot.AuthorityStateJSON);if err!=nil{return err};if !current.RevalidationRequired{return ErrRestoreNotRevalidatable};now:=s.Clock.Now().UTC();pred:=current.Revision;next:=authority.State{Revision:current.Revision+1,PredecessorRevision:&pred,Grants:append([]authority.Grant(nil),current.Grants...),RevalidationRequired:false,ChangedBy:string(assessment.Snapshot.Identity.OwnerOperatorID),ChangedAt:now};_,err=s.commitAuthorityState(ctx,assessment.trustedCurrent,next,current.Revision,"OP-AUTH-RESTORE-REVALIDATE");return err}
