package sqlite

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/developmentconexus-ops/aurora_project/internal/domain/identity"
	"github.com/developmentconexus-ops/aurora_project/internal/domain/project"
	"github.com/developmentconexus-ops/aurora_project/internal/ports"
	_ "modernc.org/sqlite"
)

var(ErrAlreadyInitialized=errors.New("state store already initialized");ErrNotInitialized=errors.New("state store is not initialized");ErrConcurrentMutation=errors.New("governing generation changed"))
type Store struct{db *sql.DB}
func Open(dataDir string)(*Store,error){stateDir:=filepath.Join(dataDir,"state");if err:=os.MkdirAll(stateDir,0o700);err!=nil{return nil,err};db,err:=sql.Open("sqlite",filepath.Join(stateDir,"aurora.db"));if err!=nil{return nil,err};db.SetMaxOpenConns(1);db.SetMaxIdleConns(1);cleanup:=func(e error)(*Store,error){_=db.Close();return nil,e};for _,p:=range[]string{"PRAGMA journal_mode=WAL","PRAGMA synchronous=FULL","PRAGMA foreign_keys=ON"}{if _,err:=db.Exec(p);err!=nil{return cleanup(fmt.Errorf("%s: %w",p,err))}};if _,err:=db.Exec(initialSchema);err!=nil{return cleanup(fmt.Errorf("apply initial schema: %w",err))};return &Store{db:db},nil}
func(s *Store)Close()error{return s.db.Close()}
func(s *Store)Bootstrap(ctx context.Context,in ports.BootstrapMutation)(ports.BootstrapResult,error){tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return ports.BootstrapResult{},err};defer tx.Rollback();var count int;if err:=tx.QueryRowContext(ctx,"SELECT COUNT(*) FROM core_state").Scan(&count);err!=nil{return ports.BootstrapResult{},err};if count!=0{return ports.BootstrapResult{},ErrAlreadyInitialized};rev:=in.CurrentAuthorityRevision;if rev==0{rev=1};now:=in.Identity.CreatedAt.UTC().Format(time.RFC3339Nano);if _,err:=tx.ExecContext(ctx,`INSERT INTO authority_revisions(authority_revision,predecessor_revision,authority_state_json,changed_by,changed_at) VALUES(?,NULL,?,?,?)`,rev,string(in.AuthorityStateJSON),in.Identity.OwnerOperatorID,now);err!=nil{return ports.BootstrapResult{},err};if _,err:=tx.ExecContext(ctx,`INSERT INTO core_state(singleton_key,aurora_id,owner_operator_id,logical_schema_version,current_authority_revision,governing_generation,governing_descriptor_hmac,created_at,updated_at) VALUES('core',?,?,?,?,?,?,?,?)`,in.Identity.AuroraID,in.Identity.OwnerOperatorID,1,rev,in.GoverningGeneration,in.GoverningMAC,now,now);err!=nil{return ports.BootstrapResult{},err};if _,err:=tx.ExecContext(ctx,`INSERT INTO records(record_id,kind,operation_id,outcome,reason,details_json,created_at,authority_revision) VALUES(?,?,?,?,?,?,?,?)`,`REC-BOOTSTRAP-1`,`AUDIT`,`OP-BOOTSTRAP-1`,`ACCEPTED`,`INITIALIZED`,`{}`,now,rev);err!=nil{return ports.BootstrapResult{},err};if err:=tx.Commit();err!=nil{return ports.BootstrapResult{},err};return ports.BootstrapResult{Identity:in.Identity,GoverningGeneration:in.GoverningGeneration},nil}
func(s *Store)LoadCurrent(ctx context.Context)(ports.CurrentSnapshot,error){var snap ports.CurrentSnapshot;var auroraID,ownerID,createdAt string;err:=s.db.QueryRowContext(ctx,`SELECT aurora_id,owner_operator_id,current_authority_revision,governing_generation,governing_descriptor_hmac,created_at FROM core_state WHERE singleton_key='core'`).Scan(&auroraID,&ownerID,&snap.CurrentAuthorityRevision,&snap.GoverningGeneration,&snap.GoverningMAC,&createdAt);if errors.Is(err,sql.ErrNoRows){return snap,ErrNotInitialized};if err!=nil{return snap,err};created,err:=time.Parse(time.RFC3339Nano,createdAt);if err!=nil{return snap,err};snap.Identity=identity.AuroraIdentity{AuroraID:identity.AuroraID(auroraID),OwnerOperatorID:identity.OperatorID(ownerID),CreatedAt:created,IdentityRevision:1,CapabilityContractVersion:"0.2.0"};if err:=s.db.QueryRowContext(ctx,`SELECT authority_state_json FROM authority_revisions WHERE authority_revision=?`,snap.CurrentAuthorityRevision).Scan(&snap.AuthorityStateJSON);err!=nil{return snap,err};rows,err:=s.db.QueryContext(ctx,`SELECT project_id,display_label,objective_summary,current_state_revision,created_at,updated_at FROM projects ORDER BY project_id`);if err!=nil{return snap,err};for rows.Next(){var p project.Project;var current sql.NullInt64;var ca,ua string;if err:=rows.Scan(&p.ProjectID,&p.DisplayLabel,&p.ObjectiveSummary,&current,&ca,&ua);err!=nil{rows.Close();return snap,err};p.CreatedAt,err=time.Parse(time.RFC3339Nano,ca);if err!=nil{rows.Close();return snap,err};p.UpdatedAt,err=time.Parse(time.RFC3339Nano,ua);if err!=nil{rows.Close();return snap,err};if current.Valid{r:=project.StateRevision(current.Int64);p.CurrentStateRevision=&r};snap.Projects=append(snap.Projects,p)};if err:=rows.Err();err!=nil{rows.Close();return snap,err};if err:=rows.Close();err!=nil{return snap,err};for _,p:=range snap.Projects{if p.CurrentStateRevision==nil{continue};state,err:=s.loadProjectStateRevision(ctx,p.ProjectID,*p.CurrentStateRevision);if err!=nil{return snap,err};snap.CurrentStates=append(snap.CurrentStates,*state)};return snap,nil}
func(s *Store)CreateProject(ctx context.Context,in ports.CreateProjectMutation)(project.Project,error){tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return project.Project{},err};defer tx.Rollback();var generation uint64;if err:=tx.QueryRowContext(ctx,`SELECT governing_generation FROM core_state WHERE singleton_key='core'`).Scan(&generation);err!=nil{return project.Project{},err};if generation!=in.ExpectedGeneration{return project.Project{},ErrConcurrentMutation};created:=in.Project.CreatedAt.UTC().Format(time.RFC3339Nano);updated:=in.Project.UpdatedAt.UTC().Format(time.RFC3339Nano);if _,err:=tx.ExecContext(ctx,`INSERT INTO projects(project_id,display_label,objective_summary,current_state_revision,created_at,updated_at) VALUES(?,?,?,NULL,?,?)`,in.Project.ProjectID,in.Project.DisplayLabel,in.Project.ObjectiveSummary,created,updated);err!=nil{return project.Project{},err};res,err:=tx.ExecContext(ctx,`UPDATE core_state SET governing_generation=?,governing_descriptor_hmac=?,updated_at=? WHERE singleton_key='core' AND governing_generation=?`,in.NewGeneration,in.GoverningMAC,updated,in.ExpectedGeneration);if err!=nil{return project.Project{},err};n,err:=res.RowsAffected();if err!=nil{return project.Project{},err};if n!=1{return project.Project{},ErrConcurrentMutation};if _,err:=tx.ExecContext(ctx,`INSERT INTO records(record_id,kind,operation_id,project_id,outcome,reason,details_json,created_at) VALUES(?,?,?,?,?,?,?,?)`,`REC-`+in.OperationID,`AUDIT`,in.OperationID,in.Project.ProjectID,`ACCEPTED`,`PROJECT_CREATED`,`{}`,updated);err!=nil{return project.Project{},err};if err:=tx.Commit();err!=nil{return project.Project{},err};return in.Project,nil}
func(s *Store)GetProject(ctx context.Context,id project.ProjectID)(project.Project,error){var p project.Project;var current sql.NullInt64;var ca,ua string;err:=s.db.QueryRowContext(ctx,`SELECT project_id,display_label,objective_summary,current_state_revision,created_at,updated_at FROM projects WHERE project_id=?`,id).Scan(&p.ProjectID,&p.DisplayLabel,&p.ObjectiveSummary,&current,&ca,&ua);if err!=nil{return p,err};p.CreatedAt,err=time.Parse(time.RFC3339Nano,ca);if err!=nil{return p,err};p.UpdatedAt,err=time.Parse(time.RFC3339Nano,ua);if err!=nil{return p,err};if current.Valid{r:=project.StateRevision(current.Int64);p.CurrentStateRevision=&r};return p,nil}
var _ ports.StateStore=(*Store)(nil)
